# Generated by Django 4.1.7 on 2023-03-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recaptcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
